// GENERATED FILE — DO NOT EDIT BY HAND.
//
// Produced by `tool/gen_supported.dart` from KaTeX's
// `docs/supported.md` (mirrors https://katex.org/docs/supported).
// Regenerate with:
//   dart run tool/gen_supported.dart <supported.md> > lib/supported_data.dart
//
// Each entry is a renderable TeX command/symbol in KaTeX category
// order. `tex` is the renderable LaTeX (the `$...$` segment of the
// doc's "rendered" cell, falling back to the bare command).
library;

/// A single catalog entry: one renderable TeX command/symbol.
class SupportedEntry {
  const SupportedEntry(this.category, this.subcategory, this.name, this.tex);

  /// Top-level KaTeX category (e.g. `Accents`, `Operators`).
  final String category;

  /// Optional subcategory within the category (e.g. `Big Operators`).
  final String? subcategory;

  /// Human-facing command label (the source text shown in the code column).
  final String name;

  /// The renderable LaTeX math source.
  final String tex;
}

/// The full catalog of KaTeX commands/symbols, in documentation order.
const List<SupportedEntry> kSupportedEntries = <SupportedEntry>[
  SupportedEntry(r'Accents', null, 'a\'', 'a\''),
  SupportedEntry(r'Accents', null, r'\tilde{a}', r'\tilde{a}'),
  SupportedEntry(r'Accents', null, r'\mathring{g}', r'\mathring{g}'),
  SupportedEntry(r'Accents', null, 'a\'\'', 'a\'\''),
  SupportedEntry(r'Accents', null, r'\widetilde{ac}', r'\widetilde{ac}'),
  SupportedEntry(r'Accents', null, r'\overgroup{AB}', r'\overgroup{AB}'),
  SupportedEntry(r'Accents', null, r'a^{\prime}', r'a^{\prime}'),
  SupportedEntry(r'Accents', null, r'\utilde{AB}', r'\utilde{AB}'),
  SupportedEntry(r'Accents', null, r'\undergroup{AB}', r'\undergroup{AB}'),
  SupportedEntry(r'Accents', null, r'\acute{a}', r'\acute{a}'),
  SupportedEntry(r'Accents', null, r'\vec{F}', r'\vec{F}'),
  SupportedEntry(r'Accents', null, r'\Overrightarrow{AB}', r'\Overrightarrow{AB}'),
  SupportedEntry(r'Accents', null, r'\bar{y}', r'\bar{y}'),
  SupportedEntry(r'Accents', null, r'\overleftarrow{AB}', r'\overleftarrow{AB}'),
  SupportedEntry(r'Accents', null, r'\overrightarrow{AB}', r'\overrightarrow{AB}'),
  SupportedEntry(r'Accents', null, r'\breve{a}', r'\breve{a}'),
  SupportedEntry(r'Accents', null, r'\underleftarrow{AB}', r'\underleftarrow{AB}'),
  SupportedEntry(r'Accents', null, r'\underrightarrow{AB}', r'\underrightarrow{AB}'),
  SupportedEntry(r'Accents', null, r'\check{a}', r'\check{a}'),
  SupportedEntry(r'Accents', null, r'\overleftharpoon{ac}', r'\overleftharpoon{ac}'),
  SupportedEntry(r'Accents', null, r'\overrightharpoon{ac}', r'\overrightharpoon{ac}'),
  SupportedEntry(r'Accents', null, r'\dot{a}', r'\dot{a}'),
  SupportedEntry(r'Accents', null, r'\overleftrightarrow{AB}', r'\overleftrightarrow{AB}'),
  SupportedEntry(r'Accents', null, r'\overbrace{AB}', r'\overbrace{AB}'),
  SupportedEntry(r'Accents', null, r'\ddot{a}', r'\ddot{a}'),
  SupportedEntry(r'Accents', null, r'\underleftrightarrow{AB}', r'\underleftrightarrow{AB}'),
  SupportedEntry(r'Accents', null, r'\underbrace{AB}', r'\underbrace{AB}'),
  SupportedEntry(r'Accents', null, r'\dddot{a}', r'\dddot{a}'),
  SupportedEntry(r'Accents', null, r'\overline{AB}', r'\overline{AB}'),
  SupportedEntry(r'Accents', null, r'\overbracket{AB}', r'\overbracket{AB}'),
  SupportedEntry(r'Accents', null, r'\ddddot{a}', r'\ddddot{a}'),
  SupportedEntry(r'Accents', null, r'\underline{AB}', r'\underline{AB}'),
  SupportedEntry(r'Accents', null, r'\underbracket{AB}', r'\underbracket{AB}'),
  SupportedEntry(r'Accents', null, r'\grave{a}', r'\grave{a}'),
  SupportedEntry(r'Accents', null, r'\underbar{X}', r'\underbar{X}'),
  SupportedEntry(r'Accents', null, r'\overlinesegment{AB}', r'\overlinesegment{AB}'),
  SupportedEntry(r'Accents', null, r'\hat{\theta}', r'\hat{\theta}'),
  SupportedEntry(r'Accents', null, r'\widecheck{ac}', r'\widecheck{ac}'),
  SupportedEntry(r'Accents', null, r'\underlinesegment{AB}', r'\underlinesegment{AB}'),
  SupportedEntry(r'Accents', null, r'\widehat{ac}', r'\widehat{ac}'),
  SupportedEntry(r'Accents', r'Accent functions inside text{…}', '\\\'{a}', '\\text{\\\'{a}}'),
  SupportedEntry(r'Accents', r'Accent functions inside text{…}', r'\~{a}', r'\text{\~{a}}'),
  SupportedEntry(r'Accents', r'Accent functions inside text{…}', r'\.{a}', r'\text{\.{a}}'),
  SupportedEntry(r'Accents', r'Accent functions inside text{…}', r'\H{a}', r'\text{\H{a}}'),
  SupportedEntry(r'Accents', r'Accent functions inside text{…}', r'\\`{a}', r'\text{\`{a}}'),
  SupportedEntry(r'Accents', r'Accent functions inside text{…}', r'\={a}', r'\text{\={a}}'),
  SupportedEntry(r'Accents', r'Accent functions inside text{…}', r'\"{a}', r'\text{\"{a}}'),
  SupportedEntry(r'Accents', r'Accent functions inside text{…}', r'\v{a}', r'\text{\v{a}}'),
  SupportedEntry(r'Accents', r'Accent functions inside text{…}', r'\^{a}', r'\text{\^{a}}'),
  SupportedEntry(r'Accents', r'Accent functions inside text{…}', r'\u{a}', r'\text{\u{a}}'),
  SupportedEntry(r'Accents', r'Accent functions inside text{…}', r'\r{a}', r'\text{\r{a}}'),
  SupportedEntry(r'Delimiters', null, r'( )', r'(~)'),
  SupportedEntry(r'Delimiters', null, r'\lparen', r'\lparen~\rparen'),
  SupportedEntry(r'Delimiters', null, r'⌈ ⌉', r'⌈~⌉'),
  SupportedEntry(r'Delimiters', null, r'\lceil', r'\lceil~\rceil'),
  SupportedEntry(r'Delimiters', null, r'\uparrow', r'\uparrow'),
  SupportedEntry(r'Delimiters', null, r'[ ]', r'[~]'),
  SupportedEntry(r'Delimiters', null, r'\lbrack', r'\lbrack~\rbrack'),
  SupportedEntry(r'Delimiters', null, r'⌊ ⌋', r'⌊~⌋'),
  SupportedEntry(r'Delimiters', null, r'\lfloor', r'\lfloor~\rfloor'),
  SupportedEntry(r'Delimiters', null, r'\downarrow', r'\downarrow'),
  SupportedEntry(r'Delimiters', null, r'\{ \}', r'\{ \}'),
  SupportedEntry(r'Delimiters', null, r'\lbrace', r'\lbrace \rbrace'),
  SupportedEntry(r'Delimiters', null, r'⎰⎱', r'⎰⎱'),
  SupportedEntry(r'Delimiters', null, r'\lmoustache', r'\lmoustache \rmoustache'),
  SupportedEntry(r'Delimiters', null, r'\updownarrow', r'\updownarrow'),
  SupportedEntry(r'Delimiters', null, r'⟨ ⟩', r'⟨~⟩'),
  SupportedEntry(r'Delimiters', null, r'\langle', r'\langle~\rangle'),
  SupportedEntry(r'Delimiters', null, r'⟮ ⟯', r'⟮~⟯'),
  SupportedEntry(r'Delimiters', null, r'\lgroup', r'\lgroup~\rgroup'),
  SupportedEntry(r'Delimiters', null, r'\Uparrow', r'\Uparrow'),
  SupportedEntry(r'Delimiters', null, r'|', r'\vert'),
  SupportedEntry(r'Delimiters', null, r'┌ ┐', r'┌ ┐'),
  SupportedEntry(r'Delimiters', null, r'\ulcorner', r'\ulcorner \urcorner'),
  SupportedEntry(r'Delimiters', null, r'\Downarrow', r'\Downarrow'),
  SupportedEntry(r'Delimiters', null, r'\|', r'\Vert'),
  SupportedEntry(r'Delimiters', null, r'└ ┘', r'└ ┘'),
  SupportedEntry(r'Delimiters', null, r'\llcorner', r'\llcorner \lrcorner'),
  SupportedEntry(r'Delimiters', null, r'\Updownarrow', r'\Updownarrow'),
  SupportedEntry(r'Delimiters', null, r'\lvert', r'\lvert~\rvert'),
  SupportedEntry(r'Delimiters', null, r'\lVert', r'\lVert~\rVert'),
  SupportedEntry(r'Delimiters', null, r'\left.', r'\left.'),
  SupportedEntry(r'Delimiters', null, r'\right.', r'\right.'),
  SupportedEntry(r'Delimiters', null, r'\backslash', r'\backslash'),
  SupportedEntry(r'Delimiters', null, r'\lang', r'\lang~\rang'),
  SupportedEntry(r'Delimiters', null, r'\lt \gt', r'\left\lt~\right\gt'),
  SupportedEntry(r'Delimiters', null, r'⟦ ⟧', r'⟦~⟧'),
  SupportedEntry(r'Delimiters', null, r'\llbracket', r'\llbracket~\rrbracket'),
  SupportedEntry(r'Delimiters', null, r'/', r'/'),
  SupportedEntry(r'Delimiters', null, r'\lBrace \rBrace', r'\lBrace~\rBrace'),
  SupportedEntry(r'Delimiters', r'Delimiter Sizing', r'\left', r'\left'),
  SupportedEntry(r'Delimiters', r'Delimiter Sizing', r'\big', r'\big'),
  SupportedEntry(r'Delimiters', r'Delimiter Sizing', r'\bigl', r'\bigl'),
  SupportedEntry(r'Delimiters', r'Delimiter Sizing', r'\bigm', r'\bigm'),
  SupportedEntry(r'Delimiters', r'Delimiter Sizing', r'\bigr', r'\bigr'),
  SupportedEntry(r'Delimiters', r'Delimiter Sizing', r'\middle', r'\middle'),
  SupportedEntry(r'Delimiters', r'Delimiter Sizing', r'\Big', r'\Big'),
  SupportedEntry(r'Delimiters', r'Delimiter Sizing', r'\Bigl', r'\Bigl'),
  SupportedEntry(r'Delimiters', r'Delimiter Sizing', r'\Bigm', r'\Bigm'),
  SupportedEntry(r'Delimiters', r'Delimiter Sizing', r'\Bigr', r'\Bigr'),
  SupportedEntry(r'Delimiters', r'Delimiter Sizing', r'\right', r'\right'),
  SupportedEntry(r'Delimiters', r'Delimiter Sizing', r'\bigg', r'\bigg'),
  SupportedEntry(r'Delimiters', r'Delimiter Sizing', r'\biggl', r'\biggl'),
  SupportedEntry(r'Delimiters', r'Delimiter Sizing', r'\biggm', r'\biggm'),
  SupportedEntry(r'Delimiters', r'Delimiter Sizing', r'\biggr', r'\biggr'),
  SupportedEntry(r'Delimiters', r'Delimiter Sizing', r'\Bigg', r'\Bigg'),
  SupportedEntry(r'Delimiters', r'Delimiter Sizing', r'\Biggl', r'\Biggl'),
  SupportedEntry(r'Delimiters', r'Delimiter Sizing', r'\Biggm', r'\Biggm'),
  SupportedEntry(r'Delimiters', r'Delimiter Sizing', r'\Biggr', r'\Biggr'),
  SupportedEntry(r'Environments', null, r'\begin{matrix} a & b \\ c & d \end{matrix}', r'\begin{matrix} a & b \\ c & d \end{matrix}'),
  SupportedEntry(r'Environments', null, r'\begin{matrix}', r'\begin{matrix}'),
  SupportedEntry(r'Environments', null, r'\begin{array}{cc}a & b\\c & d\end{array}', r'\begin{array}{cc}a & b\\c & d\end{array}'),
  SupportedEntry(r'Environments', null, r'\begin{array}{cc}', r'\begin{array}{cc}'),
  SupportedEntry(r'Environments', null, r'\begin{pmatrix} a & b \\ c & d \end{pmatrix}', r'\begin{pmatrix} a & b \\ c & d \end{pmatrix}'),
  SupportedEntry(r'Environments', null, r'\begin{pmatrix}', r'\begin{pmatrix}'),
  SupportedEntry(r'Environments', null, r'\begin{bmatrix} a & b \\ c & d \end{bmatrix}', r'\begin{bmatrix} a & b \\ c & d \end{bmatrix}'),
  SupportedEntry(r'Environments', null, r'\begin{bmatrix}', r'\begin{bmatrix}'),
  SupportedEntry(r'Environments', null, r'\begin{vmatrix} a & b \\ c & d \end{vmatrix}', r'\begin{vmatrix} a & b \\ c & d \end{vmatrix}'),
  SupportedEntry(r'Environments', null, r'\begin{vmatrix}', r'\begin{vmatrix}'),
  SupportedEntry(r'Environments', null, r'\begin{Vmatrix} a & b \\ c & d \end{Vmatrix}', r'\begin{Vmatrix} a & b \\ c & d \end{Vmatrix}'),
  SupportedEntry(r'Environments', null, r'\begin{Vmatrix}', r'\begin{Vmatrix}'),
  SupportedEntry(r'Environments', null, r'\begin{Bmatrix} a & b \\ c & d \end{Bmatrix}', r'\begin{Bmatrix} a & b \\ c & d \end{Bmatrix}'),
  SupportedEntry(r'Environments', null, r'\begin{Bmatrix}', r'\begin{Bmatrix}'),
  SupportedEntry(r'Environments', null, r'\def\arraystretch{1.5}\begin{array}{c:c:c} a & b & c \\ \hline d & e & f \\ \hdashline g & h & i \end{array}', r'\def\arraystretch{1.5}\begin{array}{c:c:c} a & b & c \\ \hline d & e & f \\ \hdashline g & h & i \end{array}'),
  SupportedEntry(r'Environments', null, r'\def\arraystretch{1.5}', r'\def\arraystretch{1.5}'),
  SupportedEntry(r'Environments', null, r'x = \begin{cases} a &\text{if } b \\ c &\text{if } d \end{cases}', r'x = \begin{cases} a &\text{if } b \\ c &\text{if } d \end{cases}'),
  SupportedEntry(r'Environments', null, r'x = \begin{cases}', r'x = \begin{cases}'),
  SupportedEntry(r'Environments', null, r'\begin{rcases} a &\text{if } b \\ c &\text{if } d \end{rcases}⇒…', r'\begin{rcases} a &\text{if } b \\ c &\text{if } d \end{rcases}⇒…'),
  SupportedEntry(r'Environments', null, r'\begin{rcases}', r'\begin{rcases}'),
  SupportedEntry(r'Environments', null, r'\begin{smallmatrix} a & b \\ c & d \end{smallmatrix}', r'\begin{smallmatrix} a & b \\ c & d \end{smallmatrix}'),
  SupportedEntry(r'Environments', null, r'\begin{smallmatrix}', r'\begin{smallmatrix}'),
  SupportedEntry(r'Environments', null, r'\sum_{\begin{subarray}{l} i\in\Lambda\\  0<j<n\end{subarray}}', r'\sum_{\begin{subarray}{l} i\in\Lambda\\  0<j<n\end{subarray}}'),
  SupportedEntry(r'Environments', null, r'\sum_{', r'\sum_{'),
  SupportedEntry(r'Environments', null, r'\begin{equation}\begin{split}a &=b+c\\&=e+f\end{split}\end{equation}', r'\begin{equation}\begin{split}a &=b+c\\&=e+f\end{split}\end{equation}'),
  SupportedEntry(r'Environments', null, r'\begin{equation}', r'\begin{equation}'),
  SupportedEntry(r'Environments', null, r'\begin{align} a&=b+c \\ d+e&=f \end{align}', r'\begin{align} a&=b+c \\ d+e&=f \end{align}'),
  SupportedEntry(r'Environments', null, r'\begin{align}', r'\begin{align}'),
  SupportedEntry(r'Environments', null, r'\begin{gather} a=b \\ e=b+c \end{gather}', r'\begin{gather} a=b \\ e=b+c \end{gather}'),
  SupportedEntry(r'Environments', null, r'\begin{gather}', r'\begin{gather}'),
  SupportedEntry(r'Environments', null, r'\begin{alignat}{2}10&x+&3&y=2\\3&x+&13&y=4\end{alignat}', r'\begin{alignat}{2}10&x+&3&y=2\\3&x+&13&y=4\end{alignat}'),
  SupportedEntry(r'Environments', null, r'\begin{alignat}{2}', r'\begin{alignat}{2}'),
  SupportedEntry(r'Environments', null, r'\begin{CD}A @>a>> B \\@VbVV @AAcA\\C @= D\end{CD}', r'\begin{CD}A @>a>> B \\@VbVV @AAcA\\C @= D\end{CD}'),
  SupportedEntry(r'Environments', null, r'\begin{CD}', r'\begin{CD}'),
  SupportedEntry(r'Environments', null, r'darray', r'darray'),
  SupportedEntry(r'Environments', null, r'displaystyle', r'displaystyle'),
  SupportedEntry(r'Environments', null, r'matrix*', r'matrix*'),
  SupportedEntry(r'Environments', null, r'\begin{matrix*}[r]', r'\begin{matrix*}[r]'),
  SupportedEntry(r'Environments', null, r'equation*', r'equation*'),
  SupportedEntry(r'Environments', null, r'\nonumber', r'\nonumber'),
  SupportedEntry(r'Environments', null, r'gathered', r'gathered'),
  SupportedEntry(r'Environments', null, r'{array}', r'{array}'),
  SupportedEntry(r'Environments', null, r'and', r'and'),
  SupportedEntry(r'HTML', null, r'\href{https://katex.org/}{\KaTeX}', r'\href{https://katex.org/}{\KaTeX}'),
  SupportedEntry(r'HTML', null, r'\url{https://katex.org/}', r'\url{https://katex.org/}'),
  SupportedEntry(r'HTML', null, r'\includegraphics[height=0.8em, totalheight=0.9em, width=0.9em, alt=KA logo]{https://katex.org/img/khan-academy.png}', r'\includegraphics[height=0.8em, totalheight=0.9em, width=0.9em, alt=KA logo]{https://katex.org/img/khan-academy.png}'),
  SupportedEntry(r'HTML', null, r'…<span id="bar" class="enclosing">…x…</span>…', r'\htmlId{bar}{x}'),
  SupportedEntry(r'HTML', null, r'…<span class="enclosing foo">…x…</span>…', r'\htmlClass{foo}{x}'),
  SupportedEntry(r'HTML', null, r'…<span style="color: red;" class="enclosing">…x…</span>…', r'\htmlStyle{color: red;}{x}'),
  SupportedEntry(r'HTML', null, r'…<span data-foo="a" data-bar="b" class="enclosing">…x…</span>…', r'\htmlData{foo=a, bar=b}{x}'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\Alpha', r'\Alpha'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\Beta', r'\Beta'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\Gamma', r'\Gamma'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\Delta', r'\Delta'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\Epsilon', r'\Epsilon'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\Zeta', r'\Zeta'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\Eta', r'\Eta'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\Theta', r'\Theta'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\Iota', r'\Iota'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\Kappa', r'\Kappa'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\Lambda', r'\Lambda'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\Mu', r'\Mu'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\Nu', r'\Nu'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\Xi', r'\Xi'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\Omicron', r'\Omicron'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\Pi', r'\Pi'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\Rho', r'\Rho'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\Sigma', r'\Sigma'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\Tau', r'\Tau'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\Upsilon', r'\Upsilon'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\Phi', r'\Phi'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\Chi', r'\Chi'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\Psi', r'\Psi'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\Omega', r'\Omega'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\varGamma', r'\varGamma'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\varDelta', r'\varDelta'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\varTheta', r'\varTheta'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\varLambda', r'\varLambda'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\varXi', r'\varXi'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\varPi', r'\varPi'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\varSigma', r'\varSigma'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\varUpsilon', r'\varUpsilon'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\varPhi', r'\varPhi'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\varPsi', r'\varPsi'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\varOmega', r'\varOmega'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\alpha', r'\alpha'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\beta', r'\beta'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\gamma', r'\gamma'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\delta', r'\delta'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\epsilon', r'\epsilon'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\zeta', r'\zeta'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\eta', r'\eta'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\theta', r'\theta'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\iota', r'\iota'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\kappa', r'\kappa'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\lambda', r'\lambda'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\mu', r'\mu'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\nu', r'\nu'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\xi', r'\xi'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\omicron', r'\omicron'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\pi', r'\pi'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\rho', r'\rho'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\sigma', r'\sigma'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\tau', r'\tau'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\upsilon', r'\upsilon'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\phi', r'\phi'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\chi', r'\chi'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\psi', r'\psi'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\omega', r'\omega'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\varepsilon', r'\varepsilon'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\varkappa', r'\varkappa'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\vartheta', r'\vartheta'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\thetasym', r'\thetasym'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\varpi', r'\varpi'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\varrho', r'\varrho'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\varsigma', r'\varsigma'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\varphi', r'\varphi'),
  SupportedEntry(r'Letters and Unicode', r'Greek Letters', r'\digamma', r'\digamma'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\imath', r'\imath'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\nabla', r'\nabla'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\Im', r'\Im'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\Reals', r'\Reals'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\text{\OE}', r'\text{\OE}'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\jmath', r'\jmath'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\partial', r'\partial'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\image', r'\image'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\wp', r'\wp'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\text{\o}', r'\text{\o}'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\aleph', r'\aleph'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\Game', r'\Game'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\Bbbk', r'\Bbbk'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\weierp', r'\weierp'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\text{\O}', r'\text{\O}'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\alef', r'\alef'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\Finv', r'\Finv'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\N', r'\N'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\Z', r'\Z'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\text{\ss}', r'\text{\ss}'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\alefsym', r'\alefsym'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\cnums', r'\cnums'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\natnums', r'\natnums'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\text{\aa}', r'\text{\aa}'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\text{\i}', r'\text{\i}'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\beth', r'\beth'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\Complex', r'\Complex'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\R', r'\R'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\text{\AA}', r'\text{\AA}'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\text{\j}', r'\text{\j}'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\gimel', r'\gimel'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\ell', r'\ell'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\Re', r'\Re'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\text{\ae}', r'\text{\ae}'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\daleth', r'\daleth'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\hbar', r'\hbar'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\real', r'\real'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\text{\AE}', r'\text{\AE}'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\eth', r'\eth'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\hslash', r'\hslash'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\reals', r'\reals'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'\text{\oe}', r'\text{\oe}'),
  SupportedEntry(r'Letters and Unicode', r'Other Letters', r'A²⁺³', r'A²⁺³'),
  SupportedEntry(r'Letters and Unicode', r'Unicode Mathematical Alphanumeric Symbols', r'\text{𝐀-𝐙 𝐚-𝐳 𝟎-𝟗}', r'\text{𝐀-𝐙 𝐚-𝐳 𝟎-𝟗}'),
  SupportedEntry(r'Letters and Unicode', r'Unicode Mathematical Alphanumeric Symbols', r'\text{𝔸-}ℤ\ 𝕜', r'\text{𝔸-}ℤ\ 𝕜'),
  SupportedEntry(r'Letters and Unicode', r'Unicode Mathematical Alphanumeric Symbols', r'\text{𝐴-𝑍 𝑎-𝑧}', r'\text{𝐴-𝑍 𝑎-𝑧}'),
  SupportedEntry(r'Letters and Unicode', r'Unicode Mathematical Alphanumeric Symbols', r'\text{𝖠-𝖹 𝖺-𝗓 𝟢-𝟫}', r'\text{𝖠-𝖹 𝖺-𝗓 𝟢-𝟫}'),
  SupportedEntry(r'Letters and Unicode', r'Unicode Mathematical Alphanumeric Symbols', r'\text{𝑨-𝒁 𝒂-𝒛}', r'\text{𝑨-𝒁 𝒂-𝒛}'),
  SupportedEntry(r'Letters and Unicode', r'Unicode Mathematical Alphanumeric Symbols', r'\text{𝗔-𝗭 𝗮-𝘇 𝟬-𝟵}', r'\text{𝗔-𝗭 𝗮-𝘇 𝟬-𝟵}'),
  SupportedEntry(r'Letters and Unicode', r'Unicode Mathematical Alphanumeric Symbols', r'\text{𝒜-𝒵}', r'\text{𝒜-𝒵}'),
  SupportedEntry(r'Letters and Unicode', r'Unicode Mathematical Alphanumeric Symbols', r'\text{𝘈-𝘡 𝘢-𝘻}', r'\text{𝘈-𝘡 𝘢-𝘻}'),
  SupportedEntry(r'Letters and Unicode', r'Unicode Mathematical Alphanumeric Symbols', r'\text{', r'\text{'),
  SupportedEntry(r'Letters and Unicode', r'Unicode Mathematical Alphanumeric Symbols', r'\text{𝙰-𝚉 𝚊-𝚣 𝟶-𝟿}', r'\text{𝙰-𝚉 𝚊-𝚣 𝟶-𝟿}'),
  SupportedEntry(r'Letters and Unicode', r'Unicode Mathematical Alphanumeric Symbols', r'\text{𝕬-𝖅 𝖆-𝖟}', r'\text{𝕬-𝖅 𝖆-𝖟}'),
  SupportedEntry(r'Layout', r'Annotation', r'\cancel{5}', r'\cancel{5}'),
  SupportedEntry(r'Layout', r'Annotation', r'\overbrace{a+b+c}^{\text{note}}', r'\overbrace{a+b+c}^{\text{note}}'),
  SupportedEntry(r'Layout', r'Annotation', r'\bcancel{5}', r'\bcancel{5}'),
  SupportedEntry(r'Layout', r'Annotation', r'\underbrace{a+b+c}_{\text{note}}', r'\underbrace{a+b+c}_{\text{note}}'),
  SupportedEntry(r'Layout', r'Annotation', r'\xcancel{ABC}', r'\xcancel{ABC}'),
  SupportedEntry(r'Layout', r'Annotation', r'\not =', r'\not ='),
  SupportedEntry(r'Layout', r'Annotation', r'\text{\sout{abc}}', r'\text{\sout{abc}}'),
  SupportedEntry(r'Layout', r'Annotation', r'\boxed{\pi=\frac c d}', r'\boxed{\pi=\frac c d}'),
  SupportedEntry(r'Layout', r'Annotation', '\$a_{\\angl n}', r'a_{\angl n}'),
  SupportedEntry(r'Layout', r'Annotation', r'a_\angln', r'a_\angln'),
  SupportedEntry(r'Layout', r'Annotation', r'\overbracket{a+b+c}^{\text{note}}', r'\overbracket{a+b+c}^{\text{note}}'),
  SupportedEntry(r'Layout', r'Annotation', r'\underbracket{a+b+c}_{\text{note}}', r'\underbracket{a+b+c}_{\text{note}}'),
  SupportedEntry(r'Layout', r'Annotation', r'\phase{-78^\circ}', r'\phase{-78^\circ}'),
  SupportedEntry(r'Layout', r'Vertical Layout', r'x_n', r'x_n'),
  SupportedEntry(r'Layout', r'Vertical Layout', r'\stackrel{!}{=}', r'\stackrel{!}{=}'),
  SupportedEntry(r'Layout', r'Vertical Layout', r'a \atop b', r'a \atop b'),
  SupportedEntry(r'Layout', r'Vertical Layout', r'e^x', r'e^x'),
  SupportedEntry(r'Layout', r'Vertical Layout', r'\overset{!}{=}', r'\overset{!}{=}'),
  SupportedEntry(r'Layout', r'Vertical Layout', 'a\\raisebox{0.25em}{\$b\$}c', r'a\raisebox{0.25em}{'),
  SupportedEntry(r'Layout', r'Vertical Layout', r'_u^o', r'_u^o'),
  SupportedEntry(r'Layout', r'Vertical Layout', r'\underset{!}{=}', r'\underset{!}{=}'),
  SupportedEntry(r'Layout', r'Vertical Layout', 'a+\\left(\\vcenter{\\hbox{\$\\frac{\\frac a b}c\$}}\\right)', r'a+\left(\vcenter{\frac{\frac a b}c}\right)'),
  SupportedEntry(r'Layout', r'Vertical Layout', r'\sum_{\substack{0<i<m\\0<j<n}}', r'\sum_{\substack{0<i<m\\0<j<n}}'),
  SupportedEntry(r'Layout', r'Overlap and Spacing', r'{=}\mathllap{/\,}', r'{=}\mathllap{/\,}'),
  SupportedEntry(r'Layout', r'Overlap and Spacing', r'\left(x^{\smash{2}}\right)', r'\left(x^{\smash{2}}\right)'),
  SupportedEntry(r'Layout', r'Overlap and Spacing', r'\mathrlap{\,/}{=}', r'\mathrlap{\,/}{=}'),
  SupportedEntry(r'Layout', r'Overlap and Spacing', r'\sqrt{\smash[b]{y}}', r'\sqrt{\smash[b]{y}}'),
  SupportedEntry(r'Layout', r'Spacing', r'\,', r'\,'),
  SupportedEntry(r'Layout', r'Spacing', r'\kern{distance}', r'\kern{distance}'),
  SupportedEntry(r'Layout', r'Spacing', r'\thinspace', r'\thinspace'),
  SupportedEntry(r'Layout', r'Spacing', r'\mkern{distance}', r'\mkern{distance}'),
  SupportedEntry(r'Layout', r'Spacing', r'\>', r'\>'),
  SupportedEntry(r'Layout', r'Spacing', r'\mskip{distance}', r'\mskip{distance}'),
  SupportedEntry(r'Layout', r'Spacing', r'\:', r'\:'),
  SupportedEntry(r'Layout', r'Spacing', r'\hskip{distance}', r'\hskip{distance}'),
  SupportedEntry(r'Layout', r'Spacing', r'\medspace', r'\medspace'),
  SupportedEntry(r'Layout', r'Spacing', r'\hspace{distance}', r'\hspace{distance}'),
  SupportedEntry(r'Layout', r'Spacing', r'\;', r'\;'),
  SupportedEntry(r'Layout', r'Spacing', r'\hspace*{distance}', r'\hspace*{distance}'),
  SupportedEntry(r'Layout', r'Spacing', r'\thickspace', r'\thickspace'),
  SupportedEntry(r'Layout', r'Spacing', r'\phantom{content}', r'\phantom{content}'),
  SupportedEntry(r'Layout', r'Spacing', r'\enspace', r'\enspace'),
  SupportedEntry(r'Layout', r'Spacing', r'\hphantom{content}', r'\hphantom{content}'),
  SupportedEntry(r'Layout', r'Spacing', r'\quad', r'\quad'),
  SupportedEntry(r'Layout', r'Spacing', r'\vphantom{content}', r'\vphantom{content}'),
  SupportedEntry(r'Layout', r'Spacing', r'\qquad', r'\qquad'),
  SupportedEntry(r'Layout', r'Spacing', r'\!', r'\!'),
  SupportedEntry(r'Layout', r'Spacing', r'~', r'~'),
  SupportedEntry(r'Layout', r'Spacing', r'\negthinspace', r'\negthinspace'),
  SupportedEntry(r'Layout', r'Spacing', r'\<space>', r'\<space>'),
  SupportedEntry(r'Layout', r'Spacing', r'\negmedspace', r'\negmedspace'),
  SupportedEntry(r'Layout', r'Spacing', r'\nobreakspace', r'\nobreakspace'),
  SupportedEntry(r'Layout', r'Spacing', r'\negthickspace', r'\negthickspace'),
  SupportedEntry(r'Layout', r'Spacing', r'\space', r'\space'),
  SupportedEntry(r'Layout', r'Spacing', r'\mathstrut', r'\mathstrut'),
  SupportedEntry(r'Layout', r'Spacing', r'\vphantom{(}', r'\vphantom{(}'),
  SupportedEntry(r'Logic and Set Theory', null, r'\forall', r'\forall'),
  SupportedEntry(r'Logic and Set Theory', null, r'\complement', r'\complement'),
  SupportedEntry(r'Logic and Set Theory', null, r'\therefore', r'\therefore'),
  SupportedEntry(r'Logic and Set Theory', null, r'\emptyset', r'\emptyset'),
  SupportedEntry(r'Logic and Set Theory', null, r'\exists', r'\exists'),
  SupportedEntry(r'Logic and Set Theory', null, r'\subset', r'\subset'),
  SupportedEntry(r'Logic and Set Theory', null, r'\because', r'\because'),
  SupportedEntry(r'Logic and Set Theory', null, r'\empty', r'\empty'),
  SupportedEntry(r'Logic and Set Theory', null, r'\exist', r'\exist'),
  SupportedEntry(r'Logic and Set Theory', null, r'\supset', r'\supset'),
  SupportedEntry(r'Logic and Set Theory', null, r'\mapsto', r'\mapsto'),
  SupportedEntry(r'Logic and Set Theory', null, r'\varnothing', r'\varnothing'),
  SupportedEntry(r'Logic and Set Theory', null, r'\nexists', r'\nexists'),
  SupportedEntry(r'Logic and Set Theory', null, r'\mid', r'\mid'),
  SupportedEntry(r'Logic and Set Theory', null, r'\to', r'\to'),
  SupportedEntry(r'Logic and Set Theory', null, r'\implies', r'\implies'),
  SupportedEntry(r'Logic and Set Theory', null, r'\in', r'\in'),
  SupportedEntry(r'Logic and Set Theory', null, r'\land', r'\land'),
  SupportedEntry(r'Logic and Set Theory', null, r'\gets', r'\gets'),
  SupportedEntry(r'Logic and Set Theory', null, r'\impliedby', r'\impliedby'),
  SupportedEntry(r'Logic and Set Theory', null, r'\isin', r'\isin'),
  SupportedEntry(r'Logic and Set Theory', null, r'\lor', r'\lor'),
  SupportedEntry(r'Logic and Set Theory', null, r'\leftrightarrow', r'\leftrightarrow'),
  SupportedEntry(r'Logic and Set Theory', null, r'\iff', r'\iff'),
  SupportedEntry(r'Logic and Set Theory', null, r'\notin', r'\notin'),
  SupportedEntry(r'Logic and Set Theory', null, r'\ni', r'\ni'),
  SupportedEntry(r'Logic and Set Theory', null, r'\notni', r'\notni'),
  SupportedEntry(r'Logic and Set Theory', null, r'\neg', r'\neg'),
  SupportedEntry(r'Logic and Set Theory', null, r'\Set{ x | x<\frac 1 2 }', r'\Set{ x \VERT x<\frac 1 2 }'),
  SupportedEntry(r'Logic and Set Theory', null, r'\set{x|x<5}', r'\set{x\VERT x<5}'),
  SupportedEntry(r'Macros', null, r'\def\foo{x^2} \foo + \foo', r'\def\foo{x^2} \foo + \foo'),
  SupportedEntry(r'Macros', null, r'\gdef\foo#1{#1^2} \foo{y} + \foo{y}', r'\gdef\foo#1{#1^2} \foo{y} + \foo{y}'),
  SupportedEntry(r'Macros', null, r'\edef\macroname#1#2…{definition to be expanded}', r'\edef\macroname#1#2…{definition to be expanded}'),
  SupportedEntry(r'Macros', null, r'\xdef\macroname#1#2…{definition to be expanded}', r'\xdef\macroname#1#2…{definition to be expanded}'),
  SupportedEntry(r'Macros', null, r'\let\foo=\bar', r'\let\foo=\bar'),
  SupportedEntry(r'Macros', null, r'\futurelet\foo\bar x', r'\futurelet\foo\bar x'),
  SupportedEntry(r'Macros', null, r'\global\def\macroname#1#2…{definition}', r'\global\def\macroname#1#2…{definition}'),
  SupportedEntry(r'Macros', null, r'\newcommand\macroname[numargs]{definition}', r'\newcommand\macroname[numargs]{definition}'),
  SupportedEntry(r'Macros', null, r'\renewcommand\macroname[numargs]{definition}', r'\renewcommand\macroname[numargs]{definition}'),
  SupportedEntry(r'Macros', null, r'\providecommand\macroname[numargs]{definition}', r'\providecommand\macroname[numargs]{definition}'),
  SupportedEntry(r'Operators', r'Big Operators', r'\sum', r'\sum'),
  SupportedEntry(r'Operators', r'Big Operators', r'\prod', r'\prod'),
  SupportedEntry(r'Operators', r'Big Operators', r'\bigotimes', r'\bigotimes'),
  SupportedEntry(r'Operators', r'Big Operators', r'\bigvee', r'\bigvee'),
  SupportedEntry(r'Operators', r'Big Operators', r'\int', r'\int'),
  SupportedEntry(r'Operators', r'Big Operators', r'\coprod', r'\coprod'),
  SupportedEntry(r'Operators', r'Big Operators', r'\bigoplus', r'\bigoplus'),
  SupportedEntry(r'Operators', r'Big Operators', r'\bigwedge', r'\bigwedge'),
  SupportedEntry(r'Operators', r'Big Operators', r'\iint', r'\iint'),
  SupportedEntry(r'Operators', r'Big Operators', r'\intop', r'\intop'),
  SupportedEntry(r'Operators', r'Big Operators', r'\bigodot', r'\bigodot'),
  SupportedEntry(r'Operators', r'Big Operators', r'\bigcap', r'\bigcap'),
  SupportedEntry(r'Operators', r'Big Operators', r'\iiint', r'\iiint'),
  SupportedEntry(r'Operators', r'Big Operators', r'\smallint', r'\smallint'),
  SupportedEntry(r'Operators', r'Big Operators', r'\biguplus', r'\biguplus'),
  SupportedEntry(r'Operators', r'Big Operators', r'\bigcup', r'\bigcup'),
  SupportedEntry(r'Operators', r'Big Operators', r'\oint', r'\oint'),
  SupportedEntry(r'Operators', r'Big Operators', r'\oiint', r'\oiint'),
  SupportedEntry(r'Operators', r'Big Operators', r'\oiiint', r'\oiiint'),
  SupportedEntry(r'Operators', r'Big Operators', r'\bigsqcup', r'\bigsqcup'),
  SupportedEntry(r'Operators', r'Binary Operators', r'+', r'+'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\cdot', r'\cdot'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\gtrdot', r'\gtrdot'),
  SupportedEntry(r'Operators', r'Binary Operators', r'x \pmod a', r'x \pmod a'),
  SupportedEntry(r'Operators', r'Binary Operators', r'-', r'-'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\cdotp', r'\cdotp'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\intercal', r'\intercal'),
  SupportedEntry(r'Operators', r'Binary Operators', r'x \pod a', r'x \pod a'),
  SupportedEntry(r'Operators', r'Binary Operators', r'/', r'/'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\centerdot', r'\centerdot'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\land', r'\land'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\rhd', r'\rhd'),
  SupportedEntry(r'Operators', r'Binary Operators', r'*', r'*'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\circ', r'\circ'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\leftthreetimes', r'\leftthreetimes'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\rightthreetimes', r'\rightthreetimes'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\amalg', r'\amalg'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\circledast', r'\circledast'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\ldotp', r'\ldotp'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\rtimes', r'\rtimes'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\And', r'\And'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\circledcirc', r'\circledcirc'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\lor', r'\lor'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\setminus', r'\setminus'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\ast', r'\ast'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\circleddash', r'\circleddash'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\lessdot', r'\lessdot'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\smallsetminus', r'\smallsetminus'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\barwedge', r'\barwedge'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\Cup', r'\Cup'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\lhd', r'\lhd'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\sqcap', r'\sqcap'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\bigcirc', r'\bigcirc'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\cup', r'\cup'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\ltimes', r'\ltimes'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\sqcup', r'\sqcup'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\bmod', r'\bmod'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\curlyvee', r'\curlyvee'),
  SupportedEntry(r'Operators', r'Binary Operators', r'x\mod a', r'x \mod a'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\times', r'\times'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\boxdot', r'\boxdot'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\curlywedge', r'\curlywedge'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\mp', r'\mp'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\unlhd', r'\unlhd'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\boxminus', r'\boxminus'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\div', r'\div'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\odot', r'\odot'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\unrhd', r'\unrhd'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\boxplus', r'\boxplus'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\divideontimes', r'\divideontimes'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\ominus', r'\ominus'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\uplus', r'\uplus'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\boxtimes', r'\boxtimes'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\dotplus', r'\dotplus'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\oplus', r'\oplus'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\vee', r'\vee'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\bullet', r'\bullet'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\doublebarwedge', r'\doublebarwedge'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\otimes', r'\otimes'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\veebar', r'\veebar'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\Cap', r'\Cap'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\doublecap', r'\doublecap'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\oslash', r'\oslash'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\wedge', r'\wedge'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\cap', r'\cap'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\doublecup', r'\doublecup'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\pm', r'\pm'),
  SupportedEntry(r'Operators', r'Binary Operators', r'\wr', r'\wr'),
  SupportedEntry(r'Operators', r'Fractions and Binomials', r'\frac{a}{b}', r'\frac{a}{b}'),
  SupportedEntry(r'Operators', r'Fractions and Binomials', r'\tfrac{a}{b}', r'\tfrac{a}{b}'),
  SupportedEntry(r'Operators', r'Fractions and Binomials', r'\genfrac ( ] {2pt}{1}a{a+1}', r'\genfrac ( ] {2pt}{1}a{a+1}'),
  SupportedEntry(r'Operators', r'Fractions and Binomials', r'{a \over b}', r'{a \over b}'),
  SupportedEntry(r'Operators', r'Fractions and Binomials', r'\dfrac{a}{b}', r'\dfrac{a}{b}'),
  SupportedEntry(r'Operators', r'Fractions and Binomials', r'{a \above{2pt} b+1}', r'{a \above{2pt} b+1}'),
  SupportedEntry(r'Operators', r'Fractions and Binomials', r'a/b', r'a/b'),
  SupportedEntry(r'Operators', r'Fractions and Binomials', r'\cfrac{a}{1 + \cfrac{1}{b}}', r'\cfrac{a}{1 + \cfrac{1}{b}}'),
  SupportedEntry(r'Operators', r'Fractions and Binomials', r'\binom{n}{k}', r'\binom{n}{k}'),
  SupportedEntry(r'Operators', r'Fractions and Binomials', r'\dbinom{n}{k}', r'\dbinom{n}{k}'),
  SupportedEntry(r'Operators', r'Fractions and Binomials', r'{n\brace k}', r'{n\brace k}'),
  SupportedEntry(r'Operators', r'Fractions and Binomials', r'{n \choose k}', r'{n \choose k}'),
  SupportedEntry(r'Operators', r'Fractions and Binomials', r'\tbinom{n}{k}', r'\tbinom{n}{k}'),
  SupportedEntry(r'Operators', r'Fractions and Binomials', r'{n\brack k}', r'{n\brack k}'),
  SupportedEntry(r'Operators', r'Math Operators', r'\arcsin', r'\arcsin'),
  SupportedEntry(r'Operators', r'Math Operators', r'\cosec', r'\cosec'),
  SupportedEntry(r'Operators', r'Math Operators', r'\deg', r'\deg'),
  SupportedEntry(r'Operators', r'Math Operators', r'\sec', r'\sec'),
  SupportedEntry(r'Operators', r'Math Operators', r'\arccos', r'\arccos'),
  SupportedEntry(r'Operators', r'Math Operators', r'\cosh', r'\cosh'),
  SupportedEntry(r'Operators', r'Math Operators', r'\dim', r'\dim'),
  SupportedEntry(r'Operators', r'Math Operators', r'\sin', r'\sin'),
  SupportedEntry(r'Operators', r'Math Operators', r'\arctan', r'\arctan'),
  SupportedEntry(r'Operators', r'Math Operators', r'\cot', r'\cot'),
  SupportedEntry(r'Operators', r'Math Operators', r'\exp', r'\exp'),
  SupportedEntry(r'Operators', r'Math Operators', r'\sinh', r'\sinh'),
  SupportedEntry(r'Operators', r'Math Operators', r'\arctg', r'\arctg'),
  SupportedEntry(r'Operators', r'Math Operators', r'\cotg', r'\cotg'),
  SupportedEntry(r'Operators', r'Math Operators', r'\hom', r'\hom'),
  SupportedEntry(r'Operators', r'Math Operators', r'\sh', r'\sh'),
  SupportedEntry(r'Operators', r'Math Operators', r'\arcctg', r'\arcctg'),
  SupportedEntry(r'Operators', r'Math Operators', r'\coth', r'\coth'),
  SupportedEntry(r'Operators', r'Math Operators', r'\ker', r'\ker'),
  SupportedEntry(r'Operators', r'Math Operators', r'\tan', r'\tan'),
  SupportedEntry(r'Operators', r'Math Operators', r'\arg', r'\arg'),
  SupportedEntry(r'Operators', r'Math Operators', r'\csc', r'\csc'),
  SupportedEntry(r'Operators', r'Math Operators', r'\lg', r'\lg'),
  SupportedEntry(r'Operators', r'Math Operators', r'\tanh', r'\tanh'),
  SupportedEntry(r'Operators', r'Math Operators', r'\ch', r'\ch'),
  SupportedEntry(r'Operators', r'Math Operators', r'\ctg', r'\ctg'),
  SupportedEntry(r'Operators', r'Math Operators', r'\ln', r'\ln'),
  SupportedEntry(r'Operators', r'Math Operators', r'\tg', r'\tg'),
  SupportedEntry(r'Operators', r'Math Operators', r'\cos', r'\cos'),
  SupportedEntry(r'Operators', r'Math Operators', r'\cth', r'\cth'),
  SupportedEntry(r'Operators', r'Math Operators', r'\log', r'\log'),
  SupportedEntry(r'Operators', r'Math Operators', r'\th', r'\th'),
  SupportedEntry(r'Operators', r'Math Operators', r'\operatorname{f}', r'\operatorname{f}'),
  SupportedEntry(r'Operators', r'Math Operators', r'\argmax', r'\argmax'),
  SupportedEntry(r'Operators', r'Math Operators', r'\injlim', r'\injlim'),
  SupportedEntry(r'Operators', r'Math Operators', r'\min', r'\min'),
  SupportedEntry(r'Operators', r'Math Operators', r'\varinjlim', r'\varinjlim'),
  SupportedEntry(r'Operators', r'Math Operators', r'\argmin', r'\argmin'),
  SupportedEntry(r'Operators', r'Math Operators', r'\lim', r'\lim'),
  SupportedEntry(r'Operators', r'Math Operators', r'\plim', r'\plim'),
  SupportedEntry(r'Operators', r'Math Operators', r'\varliminf', r'\varliminf'),
  SupportedEntry(r'Operators', r'Math Operators', r'\det', r'\det'),
  SupportedEntry(r'Operators', r'Math Operators', r'\liminf', r'\liminf'),
  SupportedEntry(r'Operators', r'Math Operators', r'\Pr', r'\Pr'),
  SupportedEntry(r'Operators', r'Math Operators', r'\varlimsup', r'\varlimsup'),
  SupportedEntry(r'Operators', r'Math Operators', r'\gcd', r'\gcd'),
  SupportedEntry(r'Operators', r'Math Operators', r'\limsup', r'\limsup'),
  SupportedEntry(r'Operators', r'Math Operators', r'\projlim', r'\projlim'),
  SupportedEntry(r'Operators', r'Math Operators', r'\varprojlim', r'\varprojlim'),
  SupportedEntry(r'Operators', r'Math Operators', r'\inf', r'\inf'),
  SupportedEntry(r'Operators', r'Math Operators', r'\max', r'\max'),
  SupportedEntry(r'Operators', r'Math Operators', r'\sup', r'\sup'),
  SupportedEntry(r'Operators', r'Math Operators', r'\operatorname*{f}', r'\operatorname*{f}'),
  SupportedEntry(r'Operators', r'Math Operators', r'\operatornamewithlimits{f}', r'\operatornamewithlimits{f}'),
  SupportedEntry(r'Relations', null, r'=', r'='),
  SupportedEntry(r'Relations', null, r'\doteqdot', r'\doteqdot'),
  SupportedEntry(r'Relations', null, r'\lessapprox', r'\lessapprox'),
  SupportedEntry(r'Relations', null, r'\smile', r'\smile'),
  SupportedEntry(r'Relations', null, r'<', r'<'),
  SupportedEntry(r'Relations', null, r'\eqcirc', r'\eqcirc'),
  SupportedEntry(r'Relations', null, r'\lesseqgtr', r'\lesseqgtr'),
  SupportedEntry(r'Relations', null, r'\sqsubset', r'\sqsubset'),
  SupportedEntry(r'Relations', null, r'>', r'>'),
  SupportedEntry(r'Relations', null, r'\eqcolon', r'\eqcolon'),
  SupportedEntry(r'Relations', null, r'\lesseqqgtr', r'\lesseqqgtr'),
  SupportedEntry(r'Relations', null, r'\sqsubseteq', r'\sqsubseteq'),
  SupportedEntry(r'Relations', null, r':', r':'),
  SupportedEntry(r'Relations', null, r'\Eqcolon', r'\Eqcolon'),
  SupportedEntry(r'Relations', null, r'\lessgtr', r'\lessgtr'),
  SupportedEntry(r'Relations', null, r'\sqsupset', r'\sqsupset'),
  SupportedEntry(r'Relations', null, r'\approx', r'\approx'),
  SupportedEntry(r'Relations', null, r'\eqqcolon', r'\eqqcolon'),
  SupportedEntry(r'Relations', null, r'\lesssim', r'\lesssim'),
  SupportedEntry(r'Relations', null, r'\sqsupseteq', r'\sqsupseteq'),
  SupportedEntry(r'Relations', null, r'\approxcolon', r'\approxcolon'),
  SupportedEntry(r'Relations', null, r'\Eqqcolon', r'\Eqqcolon'),
  SupportedEntry(r'Relations', null, r'\ll', r'\ll'),
  SupportedEntry(r'Relations', null, r'\Subset', r'\Subset'),
  SupportedEntry(r'Relations', null, r'\approxcoloncolon', r'\approxcoloncolon'),
  SupportedEntry(r'Relations', null, r'\eqsim', r'\eqsim'),
  SupportedEntry(r'Relations', null, r'\lll', r'\lll'),
  SupportedEntry(r'Relations', null, r'\subset', r'\subset'),
  SupportedEntry(r'Relations', null, r'\approxeq', r'\approxeq'),
  SupportedEntry(r'Relations', null, r'\eqslantgtr', r'\eqslantgtr'),
  SupportedEntry(r'Relations', null, r'\llless', r'\llless'),
  SupportedEntry(r'Relations', null, r'\subseteq', r'\subseteq'),
  SupportedEntry(r'Relations', null, r'\asymp', r'\asymp'),
  SupportedEntry(r'Relations', null, r'\eqslantless', r'\eqslantless'),
  SupportedEntry(r'Relations', null, r'\lt', r'\lt'),
  SupportedEntry(r'Relations', null, r'\subseteqq', r'\subseteqq'),
  SupportedEntry(r'Relations', null, r'\backepsilon', r'\backepsilon'),
  SupportedEntry(r'Relations', null, r'\equiv', r'\equiv'),
  SupportedEntry(r'Relations', null, r'\mid', r'\mid'),
  SupportedEntry(r'Relations', null, r'\succ', r'\succ'),
  SupportedEntry(r'Relations', null, r'\backsim', r'\backsim'),
  SupportedEntry(r'Relations', null, r'\fallingdotseq', r'\fallingdotseq'),
  SupportedEntry(r'Relations', null, r'\models', r'\models'),
  SupportedEntry(r'Relations', null, r'\succapprox', r'\succapprox'),
  SupportedEntry(r'Relations', null, r'\backsimeq', r'\backsimeq'),
  SupportedEntry(r'Relations', null, r'\frown', r'\frown'),
  SupportedEntry(r'Relations', null, r'\multimap', r'\multimap'),
  SupportedEntry(r'Relations', null, r'\succcurlyeq', r'\succcurlyeq'),
  SupportedEntry(r'Relations', null, r'\between', r'\between'),
  SupportedEntry(r'Relations', null, r'\ge', r'\ge'),
  SupportedEntry(r'Relations', null, r'\origof', r'\origof'),
  SupportedEntry(r'Relations', null, r'\succeq', r'\succeq'),
  SupportedEntry(r'Relations', null, r'\bowtie', r'\bowtie'),
  SupportedEntry(r'Relations', null, r'\geq', r'\geq'),
  SupportedEntry(r'Relations', null, r'\owns', r'\owns'),
  SupportedEntry(r'Relations', null, r'\succsim', r'\succsim'),
  SupportedEntry(r'Relations', null, r'\bumpeq', r'\bumpeq'),
  SupportedEntry(r'Relations', null, r'\geqq', r'\geqq'),
  SupportedEntry(r'Relations', null, r'\parallel', r'\parallel'),
  SupportedEntry(r'Relations', null, r'\Supset', r'\Supset'),
  SupportedEntry(r'Relations', null, r'\Bumpeq', r'\Bumpeq'),
  SupportedEntry(r'Relations', null, r'\geqslant', r'\geqslant'),
  SupportedEntry(r'Relations', null, r'\perp', r'\perp'),
  SupportedEntry(r'Relations', null, r'\supset', r'\supset'),
  SupportedEntry(r'Relations', null, r'\circeq', r'\circeq'),
  SupportedEntry(r'Relations', null, r'\gg', r'\gg'),
  SupportedEntry(r'Relations', null, r'\pitchfork', r'\pitchfork'),
  SupportedEntry(r'Relations', null, r'\supseteq', r'\supseteq'),
  SupportedEntry(r'Relations', null, r'\colonapprox', r'\colonapprox'),
  SupportedEntry(r'Relations', null, r'\ggg', r'\ggg'),
  SupportedEntry(r'Relations', null, r'\prec', r'\prec'),
  SupportedEntry(r'Relations', null, r'\supseteqq', r'\supseteqq'),
  SupportedEntry(r'Relations', null, r'\Colonapprox', r'\Colonapprox'),
  SupportedEntry(r'Relations', null, r'\gggtr', r'\gggtr'),
  SupportedEntry(r'Relations', null, r'\precapprox', r'\precapprox'),
  SupportedEntry(r'Relations', null, r'\thickapprox', r'\thickapprox'),
  SupportedEntry(r'Relations', null, r'\coloneq', r'\coloneq'),
  SupportedEntry(r'Relations', null, r'\gt', r'\gt'),
  SupportedEntry(r'Relations', null, r'\preccurlyeq', r'\preccurlyeq'),
  SupportedEntry(r'Relations', null, r'\thicksim', r'\thicksim'),
  SupportedEntry(r'Relations', null, r'\Coloneq', r'\Coloneq'),
  SupportedEntry(r'Relations', null, r'\gtrapprox', r'\gtrapprox'),
  SupportedEntry(r'Relations', null, r'\preceq', r'\preceq'),
  SupportedEntry(r'Relations', null, r'\trianglelefteq', r'\trianglelefteq'),
  SupportedEntry(r'Relations', null, r'\coloneqq', r'\coloneqq'),
  SupportedEntry(r'Relations', null, r'\gtreqless', r'\gtreqless'),
  SupportedEntry(r'Relations', null, r'\precsim', r'\precsim'),
  SupportedEntry(r'Relations', null, r'\triangleq', r'\triangleq'),
  SupportedEntry(r'Relations', null, r'\Coloneqq', r'\Coloneqq'),
  SupportedEntry(r'Relations', null, r'\gtreqqless', r'\gtreqqless'),
  SupportedEntry(r'Relations', null, r'\propto', r'\propto'),
  SupportedEntry(r'Relations', null, r'\trianglerighteq', r'\trianglerighteq'),
  SupportedEntry(r'Relations', null, r'\colonsim', r'\colonsim'),
  SupportedEntry(r'Relations', null, r'\gtrless', r'\gtrless'),
  SupportedEntry(r'Relations', null, r'\risingdotseq', r'\risingdotseq'),
  SupportedEntry(r'Relations', null, r'\varpropto', r'\varpropto'),
  SupportedEntry(r'Relations', null, r'\Colonsim', r'\Colonsim'),
  SupportedEntry(r'Relations', null, r'\gtrsim', r'\gtrsim'),
  SupportedEntry(r'Relations', null, r'\shortmid', r'\shortmid'),
  SupportedEntry(r'Relations', null, r'\vartriangle', r'\vartriangle'),
  SupportedEntry(r'Relations', null, r'\cong', r'\cong'),
  SupportedEntry(r'Relations', null, r'\imageof', r'\imageof'),
  SupportedEntry(r'Relations', null, r'\shortparallel', r'\shortparallel'),
  SupportedEntry(r'Relations', null, r'\vartriangleleft', r'\vartriangleleft'),
  SupportedEntry(r'Relations', null, r'\curlyeqprec', r'\curlyeqprec'),
  SupportedEntry(r'Relations', null, r'\in', r'\in'),
  SupportedEntry(r'Relations', null, r'\sim', r'\sim'),
  SupportedEntry(r'Relations', null, r'\vartriangleright', r'\vartriangleright'),
  SupportedEntry(r'Relations', null, r'\curlyeqsucc', r'\curlyeqsucc'),
  SupportedEntry(r'Relations', null, r'\Join', r'\Join'),
  SupportedEntry(r'Relations', null, r'\simcolon', r'\simcolon'),
  SupportedEntry(r'Relations', null, r'\vcentcolon', r'\vcentcolon'),
  SupportedEntry(r'Relations', null, r'\dashv', r'\dashv'),
  SupportedEntry(r'Relations', null, r'\le', r'\le'),
  SupportedEntry(r'Relations', null, r'\simcoloncolon', r'\simcoloncolon'),
  SupportedEntry(r'Relations', null, r'\vdash', r'\vdash'),
  SupportedEntry(r'Relations', null, r'\dblcolon', r'\dblcolon'),
  SupportedEntry(r'Relations', null, r'\leq', r'\leq'),
  SupportedEntry(r'Relations', null, r'\simeq', r'\simeq'),
  SupportedEntry(r'Relations', null, r'\vDash', r'\vDash'),
  SupportedEntry(r'Relations', null, r'\doteq', r'\doteq'),
  SupportedEntry(r'Relations', null, r'\leqq', r'\leqq'),
  SupportedEntry(r'Relations', null, r'\smallfrown', r'\smallfrown'),
  SupportedEntry(r'Relations', null, r'\Vdash', r'\Vdash'),
  SupportedEntry(r'Relations', null, r'\Doteq', r'\Doteq'),
  SupportedEntry(r'Relations', null, r'\leqslant', r'\leqslant'),
  SupportedEntry(r'Relations', null, r'\smallsmile', r'\smallsmile'),
  SupportedEntry(r'Relations', null, r'\Vvdash', r'\Vvdash'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\gnapprox', r'\gnapprox'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\ngeqslant', r'\ngeqslant'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\nsubseteq', r'\nsubseteq'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\precneqq', r'\precneqq'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\gneq', r'\gneq'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\ngtr', r'\ngtr'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\nsubseteqq', r'\nsubseteqq'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\precnsim', r'\precnsim'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\gneqq', r'\gneqq'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\nleq', r'\nleq'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\nsucc', r'\nsucc'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\subsetneq', r'\subsetneq'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\gnsim', r'\gnsim'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\nleqq', r'\nleqq'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\nsucceq', r'\nsucceq'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\subsetneqq', r'\subsetneqq'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\gvertneqq', r'\gvertneqq'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\nleqslant', r'\nleqslant'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\nsupseteq', r'\nsupseteq'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\succnapprox', r'\succnapprox'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\lnapprox', r'\lnapprox'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\nless', r'\nless'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\nsupseteqq', r'\nsupseteqq'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\succneqq', r'\succneqq'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\lneq', r'\lneq'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\nmid', r'\nmid'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\ntriangleleft', r'\ntriangleleft'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\succnsim', r'\succnsim'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\lneqq', r'\lneqq'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\notin', r'\notin'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\ntrianglelefteq', r'\ntrianglelefteq'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\supsetneq', r'\supsetneq'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\lnsim', r'\lnsim'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\notni', r'\notni'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\ntriangleright', r'\ntriangleright'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\supsetneqq', r'\supsetneqq'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\lvertneqq', r'\lvertneqq'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\nparallel', r'\nparallel'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\ntrianglerighteq', r'\ntrianglerighteq'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\varsubsetneq', r'\varsubsetneq'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\ncong', r'\ncong'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\nprec', r'\nprec'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\nvdash', r'\nvdash'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\varsubsetneqq', r'\varsubsetneqq'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\ne', r'\ne'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\npreceq', r'\npreceq'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\nvDash', r'\nvDash'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\varsupsetneq', r'\varsupsetneq'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\neq', r'\neq'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\nshortmid', r'\nshortmid'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\nVDash', r'\nVDash'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\varsupsetneqq', r'\varsupsetneqq'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\ngeq', r'\ngeq'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\nshortparallel', r'\nshortparallel'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\nVdash', r'\nVdash'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\ngeqq', r'\ngeqq'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\nsim', r'\nsim'),
  SupportedEntry(r'Relations', r'Negated Relations', r'\precnapprox', r'\precnapprox'),
  SupportedEntry(r'Relations', r'Arrows', r'\circlearrowleft', r'\circlearrowleft'),
  SupportedEntry(r'Relations', r'Arrows', r'\leftharpoonup', r'\leftharpoonup'),
  SupportedEntry(r'Relations', r'Arrows', r'\rArr', r'\rArr'),
  SupportedEntry(r'Relations', r'Arrows', r'\circlearrowright', r'\circlearrowright'),
  SupportedEntry(r'Relations', r'Arrows', r'\leftleftarrows', r'\leftleftarrows'),
  SupportedEntry(r'Relations', r'Arrows', r'\rarr', r'\rarr'),
  SupportedEntry(r'Relations', r'Arrows', r'\curvearrowleft', r'\curvearrowleft'),
  SupportedEntry(r'Relations', r'Arrows', r'\leftrightarrow', r'\leftrightarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\restriction', r'\restriction'),
  SupportedEntry(r'Relations', r'Arrows', r'\curvearrowright', r'\curvearrowright'),
  SupportedEntry(r'Relations', r'Arrows', r'\Leftrightarrow', r'\Leftrightarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\rightarrow', r'\rightarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\Darr', r'\Darr'),
  SupportedEntry(r'Relations', r'Arrows', r'\leftrightarrows', r'\leftrightarrows'),
  SupportedEntry(r'Relations', r'Arrows', r'\Rightarrow', r'\Rightarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\dArr', r'\dArr'),
  SupportedEntry(r'Relations', r'Arrows', r'\leftrightharpoons', r'\leftrightharpoons'),
  SupportedEntry(r'Relations', r'Arrows', r'\rightarrowtail', r'\rightarrowtail'),
  SupportedEntry(r'Relations', r'Arrows', r'\darr', r'\darr'),
  SupportedEntry(r'Relations', r'Arrows', r'\leftrightsquigarrow', r'\leftrightsquigarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\rightharpoondown', r'\rightharpoondown'),
  SupportedEntry(r'Relations', r'Arrows', r'\dashleftarrow', r'\dashleftarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\Lleftarrow', r'\Lleftarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\rightharpoonup', r'\rightharpoonup'),
  SupportedEntry(r'Relations', r'Arrows', r'\dashrightarrow', r'\dashrightarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\longleftarrow', r'\longleftarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\rightleftarrows', r'\rightleftarrows'),
  SupportedEntry(r'Relations', r'Arrows', r'\downarrow', r'\downarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\Longleftarrow', r'\Longleftarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\rightleftharpoons', r'\rightleftharpoons'),
  SupportedEntry(r'Relations', r'Arrows', r'\Downarrow', r'\Downarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\longleftrightarrow', r'\longleftrightarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\rightrightarrows', r'\rightrightarrows'),
  SupportedEntry(r'Relations', r'Arrows', r'\downdownarrows', r'\downdownarrows'),
  SupportedEntry(r'Relations', r'Arrows', r'\Longleftrightarrow', r'\Longleftrightarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\rightsquigarrow', r'\rightsquigarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\downharpoonleft', r'\downharpoonleft'),
  SupportedEntry(r'Relations', r'Arrows', r'\longmapsto', r'\longmapsto'),
  SupportedEntry(r'Relations', r'Arrows', r'\Rrightarrow', r'\Rrightarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\downharpoonright', r'\downharpoonright'),
  SupportedEntry(r'Relations', r'Arrows', r'\longrightarrow', r'\longrightarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\Rsh', r'\Rsh'),
  SupportedEntry(r'Relations', r'Arrows', r'\gets', r'\gets'),
  SupportedEntry(r'Relations', r'Arrows', r'\Longrightarrow', r'\Longrightarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\searrow', r'\searrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\Harr', r'\Harr'),
  SupportedEntry(r'Relations', r'Arrows', r'\looparrowleft', r'\looparrowleft'),
  SupportedEntry(r'Relations', r'Arrows', r'\swarrow', r'\swarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\hArr', r'\hArr'),
  SupportedEntry(r'Relations', r'Arrows', r'\looparrowright', r'\looparrowright'),
  SupportedEntry(r'Relations', r'Arrows', r'\to', r'\to'),
  SupportedEntry(r'Relations', r'Arrows', r'\harr', r'\harr'),
  SupportedEntry(r'Relations', r'Arrows', r'\Lrarr', r'\Lrarr'),
  SupportedEntry(r'Relations', r'Arrows', r'\twoheadleftarrow', r'\twoheadleftarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\hookleftarrow', r'\hookleftarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\lrArr', r'\lrArr'),
  SupportedEntry(r'Relations', r'Arrows', r'\twoheadrightarrow', r'\twoheadrightarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\hookrightarrow', r'\hookrightarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\lrarr', r'\lrarr'),
  SupportedEntry(r'Relations', r'Arrows', r'\Uarr', r'\Uarr'),
  SupportedEntry(r'Relations', r'Arrows', r'\iff', r'\iff'),
  SupportedEntry(r'Relations', r'Arrows', r'\Lsh', r'\Lsh'),
  SupportedEntry(r'Relations', r'Arrows', r'\uArr', r'\uArr'),
  SupportedEntry(r'Relations', r'Arrows', r'\impliedby', r'\impliedby'),
  SupportedEntry(r'Relations', r'Arrows', r'\mapsto', r'\mapsto'),
  SupportedEntry(r'Relations', r'Arrows', r'\uarr', r'\uarr'),
  SupportedEntry(r'Relations', r'Arrows', r'\implies', r'\implies'),
  SupportedEntry(r'Relations', r'Arrows', r'\nearrow', r'\nearrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\uparrow', r'\uparrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\Larr', r'\Larr'),
  SupportedEntry(r'Relations', r'Arrows', r'\nleftarrow', r'\nleftarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\Uparrow', r'\Uparrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\lArr', r'\lArr'),
  SupportedEntry(r'Relations', r'Arrows', r'\nLeftarrow', r'\nLeftarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\updownarrow', r'\updownarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\larr', r'\larr'),
  SupportedEntry(r'Relations', r'Arrows', r'\nleftrightarrow', r'\nleftrightarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\Updownarrow', r'\Updownarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\leadsto', r'\leadsto'),
  SupportedEntry(r'Relations', r'Arrows', r'\nLeftrightarrow', r'\nLeftrightarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\upharpoonleft', r'\upharpoonleft'),
  SupportedEntry(r'Relations', r'Arrows', r'\leftarrow', r'\leftarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\nrightarrow', r'\nrightarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\upharpoonright', r'\upharpoonright'),
  SupportedEntry(r'Relations', r'Arrows', r'\Leftarrow', r'\Leftarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\nRightarrow', r'\nRightarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\upuparrows', r'\upuparrows'),
  SupportedEntry(r'Relations', r'Arrows', r'\leftarrowtail', r'\leftarrowtail'),
  SupportedEntry(r'Relations', r'Arrows', r'\nwarrow', r'\nwarrow'),
  SupportedEntry(r'Relations', r'Arrows', r'\leftharpoondown', r'\leftharpoondown'),
  SupportedEntry(r'Relations', r'Arrows', r'\Rarr', r'\Rarr'),
  SupportedEntry(r'Relations', r'Extensible Arrows', r'\xleftarrow{abc}', r'\xleftarrow{abc}'),
  SupportedEntry(r'Relations', r'Extensible Arrows', r'\xrightarrow[under]{over}', r'\xrightarrow[under]{over}'),
  SupportedEntry(r'Relations', r'Extensible Arrows', r'\xLeftarrow{abc}', r'\xLeftarrow{abc}'),
  SupportedEntry(r'Relations', r'Extensible Arrows', r'\xRightarrow{abc}', r'\xRightarrow{abc}'),
  SupportedEntry(r'Relations', r'Extensible Arrows', r'\xleftrightarrow{abc}', r'\xleftrightarrow{abc}'),
  SupportedEntry(r'Relations', r'Extensible Arrows', r'\xLeftrightarrow{abc}', r'\xLeftrightarrow{abc}'),
  SupportedEntry(r'Relations', r'Extensible Arrows', r'\xhookleftarrow{abc}', r'\xhookleftarrow{abc}'),
  SupportedEntry(r'Relations', r'Extensible Arrows', r'\xhookrightarrow{abc}', r'\xhookrightarrow{abc}'),
  SupportedEntry(r'Relations', r'Extensible Arrows', r'\xtwoheadleftarrow{abc}', r'\xtwoheadleftarrow{abc}'),
  SupportedEntry(r'Relations', r'Extensible Arrows', r'\xtwoheadrightarrow{abc}', r'\xtwoheadrightarrow{abc}'),
  SupportedEntry(r'Relations', r'Extensible Arrows', r'\xleftharpoonup{abc}', r'\xleftharpoonup{abc}'),
  SupportedEntry(r'Relations', r'Extensible Arrows', r'\xrightharpoonup{abc}', r'\xrightharpoonup{abc}'),
  SupportedEntry(r'Relations', r'Extensible Arrows', r'\xleftharpoondown{abc}', r'\xleftharpoondown{abc}'),
  SupportedEntry(r'Relations', r'Extensible Arrows', r'\xrightharpoondown{abc}', r'\xrightharpoondown{abc}'),
  SupportedEntry(r'Relations', r'Extensible Arrows', r'\xleftrightharpoons{abc}', r'\xleftrightharpoons{abc}'),
  SupportedEntry(r'Relations', r'Extensible Arrows', r'\xrightleftharpoons{abc}', r'\xrightleftharpoons{abc}'),
  SupportedEntry(r'Relations', r'Extensible Arrows', r'\xtofrom{abc}', r'\xtofrom{abc}'),
  SupportedEntry(r'Relations', r'Extensible Arrows', r'\xmapsto{abc}', r'\xmapsto{abc}'),
  SupportedEntry(r'Relations', r'Extensible Arrows', r'\xlongequal{abc}', r'\xlongequal{abc}'),
  SupportedEntry(r'Special Notation', r'Bra-ket Notation', r'\bra{\phi}', r'\bra{\phi}'),
  SupportedEntry(r'Special Notation', r'Bra-ket Notation', r'\ket{\psi}', r'\ket{\psi}'),
  SupportedEntry(r'Special Notation', r'Bra-ket Notation', r'\braket{\phi|\psi}', r'\braket{\phi\VERT\psi}'),
  SupportedEntry(r'Special Notation', r'Bra-ket Notation', r'\Bra{\phi}', r'\Bra{\phi}'),
  SupportedEntry(r'Special Notation', r'Bra-ket Notation', r'\Ket{\psi}', r'\Ket{\psi}'),
  SupportedEntry(r'Special Notation', r'Bra-ket Notation', r'\Braket{ ϕ | \frac{∂^2}{∂ t^2} | ψ }', r'\Braket{ ϕ \VERT \frac{∂^2}{∂ t^2} \VERT ψ }'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Font', r'\mathrm{Ab0}', r'\mathrm{Ab0}'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Font', r'\mathbf{Ab0}', r'\mathbf{Ab0}'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Font', r'\mathsf{Ab0}', r'\mathsf{Ab0}'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Font', r'\mathnormal{Ab0}', r'\mathnormal{Ab0}'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Font', r'\textbf{Ab0}', r'\textbf{Ab0}'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Font', r'\textsf{Ab0}', r'\textsf{Ab0}'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Font', r'\textrm{Ab0}', r'\textrm{Ab0}'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Font', r'\bf Ab0', r'\bf Ab0'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Font', r'\sf Ab0', r'\sf Ab0'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Font', r'\rm Ab0', r'\rm Ab0'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Font', r'\bold{Ab0}', r'\bold{Ab0}'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Font', r'\mathsfit{Ab0}', r'\mathsfit{Ab0}'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Font', r'\textnormal{Ab0}', r'\textnormal{Ab0}'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Font', r'\boldsymbol{Ab0}', r'\boldsymbol{Ab0}'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Font', r'\Bbb{AB}', r'\Bbb{AB}'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Font', r'\text{Ab0}', r'\text{Ab0}'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Font', r'\bm{Ab0}', r'\bm{Ab0}'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Font', r'\mathbb{AB}', r'\mathbb{AB}'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Font', r'\textup{Ab0}', r'\textup{Ab0}'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Font', r'\textmd{Ab0}', r'\textmd{Ab0}'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Font', r'\frak{Ab0}', r'\frak{Ab0}'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Font', r'\mathit{Ab0}', r'\mathit{Ab0}'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Font', r'\mathtt{Ab0}', r'\mathtt{Ab0}'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Font', r'\mathfrak{Ab0}', r'\mathfrak{Ab0}'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Font', r'\textit{Ab0}', r'\textit{Ab0}'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Font', r'\texttt{Ab0}', r'\texttt{Ab0}'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Font', r'\mathcal{AB0}', r'\mathcal{AB0}'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Font', r'\it Ab0', r'\it Ab0'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Font', r'\tt Ab0', r'\tt Ab0'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Font', r'\cal AB0', r'\cal AB0'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Font', r'\emph{Ab0}', r'\emph{Ab0}'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Font', r'\mathscr{AB}', r'\mathscr{AB}'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Size', r'\Huge AB', r'\Huge AB'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Size', r'\normalsize AB', r'\normalsize AB'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Size', r'\huge AB', r'\huge AB'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Size', r'\small AB', r'\small AB'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Size', r'\LARGE AB', r'\LARGE AB'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Size', r'\footnotesize AB', r'\footnotesize AB'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Size', r'\Large AB', r'\Large AB'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Size', r'\scriptsize AB', r'\scriptsize AB'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Size', r'\large AB', r'\large AB'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Size', r'\tiny AB', r'\tiny AB'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Style', r'\displaystyle\sum_{i=1}^n', r'\displaystyle\sum_{i=1}^n'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Style', r'\textstyle\sum_{i=1}^n', r'\textstyle\sum_{i=1}^n'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Style', r'\scriptstyle x', r'\scriptstyle x'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Style', r'\scriptscriptstyle x', r'\scriptscriptstyle x'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Style', r'\lim\limits_x', r'\lim\limits_x'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Style', r'\lim\nolimits_x', r'\lim\nolimits_x'),
  SupportedEntry(r'Style, Color, Size, and Font', r'Style', r'\verb!x^2!', r'\verb!x^2!'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\dots', r'\dots'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\KaTeX', r'\KaTeX'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\%', r'\%'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\cdots', r'\cdots'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\LaTeX', r'\LaTeX'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\#', r'\#'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\ddots', r'\ddots'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\TeX', r'\TeX'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\&', r'\&'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\ldots', r'\ldots'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\nabla', r'\nabla'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\_', r'\_'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\vdots', r'\vdots'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\infty', r'\infty'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\text{\textunderscore}', r'\text{\textunderscore}'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\dotsb', r'\dotsb'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\infin', r'\infin'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\text{--}', r'\text{--}'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\dotsc', r'\dotsc'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\checkmark', r'\checkmark'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\text{\textendash}', r'\text{\textendash}'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\dotsi', r'\dotsi'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\dag', r'\dag'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\text{---}', r'\text{---}'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\dotsm', r'\dotsm'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\dagger', r'\dagger'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\text{\textemdash}', r'\text{\textemdash}'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\dotso', r'\dotso'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\text{\textdagger}', r'\text{\textdagger}'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\text{\textasciitilde}', r'\text{\textasciitilde}'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\sdot', r'\sdot'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\ddag', r'\ddag'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\text{\textasciicircum}', r'\text{\textasciicircum}'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\mathellipsis', r'\mathellipsis'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\ddagger', r'\ddagger'),
  SupportedEntry(r'Symbols and Punctuation', null, r'`', r'`'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\text{\textellipsis}', r'\text{\textellipsis}'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\text{\textdaggerdbl}', r'\text{\textdaggerdbl}'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\text{\textquoteleft}', r'\text{\textquoteleft}'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\Box', r'\Box'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\Dagger', r'\Dagger'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\lq', r'\lq'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\square', r'\square'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\angle', r'\angle'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\text{\textquoteright}', r'\text{\textquoteright}'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\blacksquare', r'\blacksquare'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\measuredangle', r'\measuredangle'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\rq', r'\rq'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\triangle', r'\triangle'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\sphericalangle', r'\sphericalangle'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\text{\textquotedblleft}', r'\text{\textquotedblleft}'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\triangledown', r'\triangledown'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\top', r'\top'),
  SupportedEntry(r'Symbols and Punctuation', null, r'"', r'"'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\triangleleft', r'\triangleleft'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\bot', r'\bot'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\text{\textquotedblright}', r'\text{\textquotedblright}'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\triangleright', r'\triangleright'),
  SupportedEntry(r'Symbols and Punctuation', null, '\\\$', '\\\$'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\colon', r'\colon'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\bigtriangledown', r'\bigtriangledown'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\text{\textdollar}', r'\text{\textdollar}'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\backprime', r'\backprime'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\bigtriangleup', r'\bigtriangleup'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\pounds', r'\pounds'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\prime', r'\prime'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\blacktriangle', r'\blacktriangle'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\mathsterling', r'\mathsterling'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\text{\textless}', r'\text{\textless}'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\blacktriangledown', r'\blacktriangledown'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\text{\textsterling}', r'\text{\textsterling}'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\text{\textgreater}', r'\text{\textgreater}'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\blacktriangleleft', r'\blacktriangleleft'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\yen', r'\yen'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\text{\textbar}', r'\text{\textbar}'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\blacktriangleright', r'\blacktriangleright'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\surd', r'\surd'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\text{\textbardbl}', r'\text{\textbardbl}'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\diamond', r'\diamond'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\degree', r'\degree'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\text{\textbraceleft}', r'\text{\textbraceleft}'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\Diamond', r'\Diamond'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\text{\textdegree}', r'\text{\textdegree}'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\text{\textbraceright}', r'\text{\textbraceright}'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\lozenge', r'\lozenge'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\mho', r'\mho'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\text{\textbackslash}', r'\text{\textbackslash}'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\blacklozenge', r'\blacklozenge'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\diagdown', r'\diagdown'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\text{\P}', r'\text{\P}'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\star', r'\star'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\diagup', r'\diagup'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\text{\S}', r'\text{\S}'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\bigstar', r'\bigstar'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\flat', r'\flat'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\text{\sect}', r'\text{\sect}'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\clubsuit', r'\clubsuit'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\natural', r'\natural'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\copyright', r'\copyright'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\clubs', r'\clubs'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\sharp', r'\sharp'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\circledR', r'\circledR'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\diamondsuit', r'\diamondsuit'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\heartsuit', r'\heartsuit'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\text{\textregistered}', r'\text{\textregistered}'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\diamonds', r'\diamonds'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\hearts', r'\hearts'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\circledS', r'\circledS'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\spadesuit', r'\spadesuit'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\spades', r'\spades'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\text{\textcircled a}', r'\text{\textcircled a}'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\maltese', r'\maltese'),
  SupportedEntry(r'Symbols and Punctuation', null, r'\minuso', r'\minuso'),
  SupportedEntry(r'Units', null, r'\rule{1em}{1em}', r'\rule{1em}{1em}'),
  SupportedEntry(r'Units', null, r'\scriptscriptstyle\rule{1em}{1em}', r'\scriptscriptstyle\rule{1em}{1em}'),
  SupportedEntry(r'Units', null, r'\huge\rule{1em}{1em}', r'\huge\rule{1em}{1em}'),
  SupportedEntry(r'Units', null, r'\rule{18mu}{18mu}', r'\rule{18mu}{18mu}'),
  SupportedEntry(r'Units', null, r'\scriptscriptstyle\rule{18mu}{18mu}', r'\scriptscriptstyle\rule{18mu}{18mu}'),
  SupportedEntry(r'Units', null, r'\huge\rule{18mu}{18mu}', r'\huge\rule{18mu}{18mu}'),
  SupportedEntry(r'Units', null, r'\rule{10pt}{10pt}', r'\rule{10pt}{10pt}'),
  SupportedEntry(r'Units', null, r'\scriptscriptstyle\rule{10pt}{10pt}', r'\scriptscriptstyle\rule{10pt}{10pt}'),
  SupportedEntry(r'Units', null, r'\huge\rule{10pt}{10pt}', r'\huge\rule{10pt}{10pt}'),
];
