// GENERATED FILE — DO NOT EDIT.
//
// Generated by tool/gen_spacing.dart from KaTeX 0.17.0
// (reference/node_modules/katex/src/spacingData.ts).
// ignore_for_file: type=lint

import 'package:katex/src/symbols/symbols.dart';

/// 3 mu — thin space.
const Mu thinspace = Mu(3);

/// 4 mu — medium space.
const Mu mediumspace = Mu(4);

/// 5 mu — thick space.
const Mu thickspace = Mu(5);

/// Inter-atom spacings for display and text styles.
///
/// Mirrors KaTeX `spacings[left][right]`; a missing entry
/// means no spacing.
const Map<MathClass, Map<MathClass, Mu>> spacings = {
  MathClass.mord: {
    MathClass.mop: thinspace,
    MathClass.mbin: mediumspace,
    MathClass.mrel: thickspace,
    MathClass.minner: thinspace,
  },
  MathClass.mop: {
    MathClass.mord: thinspace,
    MathClass.mop: thinspace,
    MathClass.mrel: thickspace,
    MathClass.minner: thinspace,
  },
  MathClass.mbin: {
    MathClass.mord: mediumspace,
    MathClass.mop: mediumspace,
    MathClass.mopen: mediumspace,
    MathClass.minner: mediumspace,
  },
  MathClass.mrel: {
    MathClass.mord: thickspace,
    MathClass.mop: thickspace,
    MathClass.mopen: thickspace,
    MathClass.minner: thickspace,
  },
  MathClass.mopen: {},
  MathClass.mclose: {
    MathClass.mop: thinspace,
    MathClass.mbin: mediumspace,
    MathClass.mrel: thickspace,
    MathClass.minner: thinspace,
  },
  MathClass.mpunct: {
    MathClass.mord: thinspace,
    MathClass.mop: thinspace,
    MathClass.mrel: thickspace,
    MathClass.mopen: thinspace,
    MathClass.mclose: thinspace,
    MathClass.mpunct: thinspace,
    MathClass.minner: thinspace,
  },
  MathClass.minner: {
    MathClass.mord: thinspace,
    MathClass.mop: thinspace,
    MathClass.mbin: mediumspace,
    MathClass.mrel: thickspace,
    MathClass.mopen: thinspace,
    MathClass.mpunct: thinspace,
    MathClass.minner: thinspace,
  },
};

/// Inter-atom spacings for script and scriptscript styles.
///
/// Mirrors KaTeX `tightSpacings[left][right]`.
const Map<MathClass, Map<MathClass, Mu>> tightSpacings = {
  MathClass.mord: {MathClass.mop: thinspace},
  MathClass.mop: {MathClass.mord: thinspace, MathClass.mop: thinspace},
  MathClass.mbin: {},
  MathClass.mrel: {},
  MathClass.mopen: {},
  MathClass.mclose: {MathClass.mop: thinspace},
  MathClass.mpunct: {},
  MathClass.minner: {MathClass.mop: thinspace},
};
