name: katex_flutter

on:
  push:
    paths:
      - "packages/katex/**"
      - "packages/katex_flutter/**"
      - ".github/workflows/katex_flutter.yml"
  pull_request:
    paths:
      - "packages/katex/**"
      - "packages/katex_flutter/**"
      - ".github/workflows/katex_flutter.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/katex_flutter
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
